# This rule is not used by the project picodata-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to picodata.picodata.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: picodata-operator
    app.kubernetes.io/managed-by: kustomize
  name: picoclusterdb-viewer-role
rules:
- apiGroups:
  - picodata.picodata.io
  resources:
  - picoclusterdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - picodata.picodata.io
  resources:
  - picoclusterdbs/status
  verbs:
  - get
