apiVersion: picodata.picodata.io/v1
kind: PicoclusterDB
metadata:
  name: picodata-sample
  namespace: picodata
spec:
  image:
    repository: git.picodata.io:5000/picodata/plugin/radix
    tag: "radix-1.0.0:latest"
    pullPolicy: Never

  clusterName: picodata-sample

  adminPassword:
    secretName: picodata-admin-secret
    key: password

  cluster:
    defaultReplicationFactor: 1
    defaultBucketCount: 16384

  tiers:
    # Тир-арбитр: участвует в raft-голосовании, не хранит пользовательские данные.
    # 2 репликасета, RF=1 → 2 пода.
    - name: arbiter
      replicas: 2
      replicationFactor: 1
      canVote: true
      storage:
        size: 1Gi
      memtx:
        memory: "64M"
      vinyl:
        memory: "32M"
        cache: "16M"
      pg:
        enabled: false
      log:
        level: info
        format: plain
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

    # Основной тир с плагином Radix.
    # 2 репликасета, RF=2 → 4 пода.
    # shareDir указывает на директорию внутри образа, где находится .so плагина.
    - name: default
      replicas: 2
      replicationFactor: 3
      canVote: false
      shareDir: /usr/share/picodata
      plugins:
        - name: radix
          version: "1.0.0"
          migrationContext:
            tier_for_db_0: "default"
            tier_for_db_1: "default"
            tier_for_db_2: "default"
            tier_for_db_3: "default"
            tier_for_db_4: "default"
            tier_for_db_5: "default"
            tier_for_db_6: "default"
            tier_for_db_7: "default"
            tier_for_db_8: "default"
            tier_for_db_9: "default"
            tier_for_db_10: "default"
            tier_for_db_11: "default"
            tier_for_db_12: "default"
            tier_for_db_13: "default"
            tier_for_db_14: "default"
            tier_for_db_15: "default"
            unlogged: ""
          services:
            - name: radix
              listenerPort: 8082
      storage:
        size: 2Gi
      memtx:
        memory: "256M"
      vinyl:
        memory: "64M"
        cache: "32M"
      pg:
        enabled: true
        ssl: false
      log:
        level: info
        format: plain
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
